# Generated by Django 5.2 on 2025-04-09 20:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0002_ticket'),
    ]

    operations = [
        migrations.AddField(
            model_name='client',
            name='segment',
            field=models.CharField(choices=[('regular', 'Постоянный клиент'), ('one_time', 'Одноразовый'), ('corporate', 'Корпоративный')], default='one_time', max_length=20, verbose_name='Сегмент'),
        ),
        migrations.AlterField(
            model_name='client',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
